FROM greatfox/oraclejdk8
MAINTAINER Liang Dong <greatfox@gmail.com>

RUN wget -qO /dev/stdout http://download.eclipse.org/jetty/stable-9/dist/jetty-distribution-9.2.7.v20150116.tar.gz | tar zxv -C /opt/

EXPOSE 8080

